# Generated by Django 4.1 on 2022-08-25 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=150, verbose_name='Метод нанесения')),
            ],
            options={
                'verbose_name': 'Метод нанесения',
                'verbose_name_plural': 'Методы нанесения',
            },
        ),
        migrations.CreateModel(
            name='Conditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=150, verbose_name='Условия')),
            ],
            options={
                'verbose_name': 'Условие',
                'verbose_name_plural': 'Условия',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150, verbose_name='Наименование')),
                ('ral', models.CharField(max_length=50, verbose_name='RAL')),
                ('batch', models.SmallIntegerField(unique=True, verbose_name='Номер партии №')),
                ('consumer', models.CharField(max_length=150, verbose_name='Потребитель')),
                ('qr', models.ImageField(blank=True, upload_to='QR/%Y/%m/%d/', verbose_name='QR')),
                ('note', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Время создания')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RalGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SmallIntegerField(verbose_name='RAL group')),
            ],
            options={
                'verbose_name': 'Цветовая группа',
                'verbose_name_plural': 'Цветовые группы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('note', models.TextField(blank=True, verbose_name='Описание')),
                ('delta_L', models.FloatField(default=0, verbose_name='L')),
                ('delta_a', models.FloatField(default=0, verbose_name='a')),
                ('delta_b', models.FloatField(default=0, verbose_name='b')),
                ('delta_E', models.FloatField(default=0, verbose_name='E')),
                ('L', models.FloatField(default=0, verbose_name='*L')),
                ('a', models.FloatField(default=0, verbose_name='*a')),
                ('b', models.FloatField(default=0, verbose_name='*b')),
                ('application_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='color.applicationmethod')),
                ('conditions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='color.conditions')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='color.product')),
                ('ral_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='color.ralgroup')),
            ],
            options={
                'verbose_name': 'Образец',
                'verbose_name_plural': 'Образцы',
                'ordering': ['-created_at'],
            },
        ),
    ]
